-- Mako Production System (Mako Gold Mine, Petowal Mining Company S.A.) schema for PostgreSQL
-- Generated by mps/build_ddl.py from mps/schema/mps_schema.json version 0.1.0. Do not edit; regenerate.
-- Safe to re-run on an existing database: tables use IF NOT EXISTS, views are dropped and recreated,
-- seeds are inserted only when missing. Structural changes to existing tables need a migration.
-- Run: psql -v ON_ERROR_STOP=1 -1 -f schema_postgres.sql  (single transaction; needs plpgsql, PostgreSQL 13 or later)
--
-- Naming: Excel table -> SQL table (primary key)
--   tblPlant           sheet Plant              -> plant_daily (date)
--   tblMovement        sheet Mining_Movements   -> movement (id)
--   tblMiningDaily     sheet Mining_Daily       -> mining_daily (date)
--   tblFleet           sheet Fleet              -> fleet (id)
--   tblSafety          sheet Safety             -> safety_daily (date)
--   tblSafetyHistory   sheet Config             -> safety_history (month)
--   tblGold            sheet Gold               -> gold (id)
--   tblBudget          sheet Budget             -> budget (month)
--   tblCommentary      sheet Commentary         -> commentary (id)
--   tblSources         sheet Lists              -> sources (source)
--   tblDestinations    sheet Lists              -> destinations (destination)
--   tblStockpiles      sheet Config             -> stockpiles (stockpile)
--   lists           -> ref_<list>(code, sort_order), one row per drop-down value
-- Columns are the Excel field names in lower case. Units: tonnes dry metric, grades g/t,
-- gold troy ounces (31.1035 g), percentages stored as fractions 0 to 1.
-- Types: date DATE, text TEXT, list TEXT + FOREIGN KEY, number NUMERIC(18,4), int INTEGER, pct NUMERIC(9,6) CHECK 0..1.
-- CHECK constraints come from the schema min/max; NULL means not reported and always passes.
-- Calculated fields are GENERATED ALWAYS AS ... STORED; Excel lookups (source type, destination type)
-- are LEFT JOINs in the <table>_calc views.
-- kpi_daily reproduces the workbook Calc_Daily day columns; kpi_monthly gives the month totals
-- with ratios recomputed from summed numerators and denominators.
-- Excel-only helper fields not carried to SQL: tblCommentary.Seq_Day, tblCommentary.Key_Day.

-- ---------------------------------------------------------------- reference lists (drop-down values)
CREATE TABLE IF NOT EXISTS ref_shift (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_material (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_area (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_equipment_class (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_gold_movement_type (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_yes_no (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_source_type (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ref_destination_type (
    code TEXT PRIMARY KEY,
    sort_order INTEGER NOT NULL
);

-- ---------------------------------------------------------------- reference tables (Lists and Config sheets)
CREATE TABLE IF NOT EXISTS sources (
    source TEXT NOT NULL,
    type TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_sources PRIMARY KEY (source),
    CONSTRAINT fk_sources_type FOREIGN KEY (type) REFERENCES ref_source_type (code)
);
CREATE TABLE IF NOT EXISTS destinations (
    destination TEXT NOT NULL,
    type TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_destinations PRIMARY KEY (destination),
    CONSTRAINT fk_destinations_type FOREIGN KEY (type) REFERENCES ref_destination_type (code)
);
CREATE TABLE IF NOT EXISTS stockpiles (
    stockpile TEXT NOT NULL,
    opening_t NUMERIC(18,4),
    opening_gpt NUMERIC(18,4),
    plant_feed TEXT,
    survey_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_stockpiles PRIMARY KEY (stockpile),
    CONSTRAINT fk_stockpiles_plant_feed FOREIGN KEY (plant_feed) REFERENCES ref_yes_no (code),
    CONSTRAINT fk_stockpiles_sources FOREIGN KEY (stockpile) REFERENCES sources (source),
    CONSTRAINT fk_stockpiles_destinations FOREIGN KEY (stockpile) REFERENCES destinations (destination)
);

-- ---------------------------------------------------------------- input tables
-- Processing plant, one row per day (owner: Processing (met accountant / shift supervisor))
CREATE TABLE IF NOT EXISTS plant_daily (
    date DATE NOT NULL,
    crushed_t NUMERIC(18,4),
    milled_t NUMERIC(18,4),
    head_grade_gpt NUMERIC(18,4),
    tails_grade_gpt NUMERIC(18,4),
    gravity_gold_oz NUMERIC(18,4),
    gold_poured_oz NUMERIC(18,4),
    mill_run_h NUMERIC(18,4),
    mill_planned_maint_h NUMERIC(18,4),
    mill_unplanned_down_h NUMERIC(18,4),
    crusher_run_h NUMERIC(18,4),
    cyanide_kg NUMERIC(18,4),
    lime_kg NUMERIC(18,4),
    grinding_media_kg NUMERIC(18,4),
    power_kwh NUMERIC(18,4),
    raw_water_m3 NUMERIC(18,4),
    gic_oz NUMERIC(18,4),
    comments TEXT,
    feed_oz NUMERIC(18,4) GENERATED ALWAYS AS (milled_t * head_grade_gpt / 31.1035) STORED,
    tails_oz NUMERIC(18,4) GENERATED ALWAYS AS (milled_t * tails_grade_gpt / 31.1035) STORED,
    recovered_oz NUMERIC(18,4) GENERATED ALWAYS AS (milled_t * (head_grade_gpt - tails_grade_gpt) / 31.1035) STORED,
    recovery_pct NUMERIC(9,6) GENERATED ALWAYS AS (CASE WHEN head_grade_gpt > 0 THEN 1 - tails_grade_gpt / head_grade_gpt END) STORED,
    throughput_tph NUMERIC(18,4) GENERATED ALWAYS AS (CASE WHEN mill_run_h > 0 THEN milled_t / mill_run_h END) STORED,
    availability_pct NUMERIC(9,6) GENERATED ALWAYS AS ((24 - mill_planned_maint_h - mill_unplanned_down_h) / 24.0) STORED,
    utilisation_pct NUMERIC(9,6) GENERATED ALWAYS AS (CASE WHEN (24 - mill_planned_maint_h - mill_unplanned_down_h) > 0 THEN mill_run_h / (24 - mill_planned_maint_h - mill_unplanned_down_h) END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_plant_daily PRIMARY KEY (date),
    CONSTRAINT ck_plant_daily_crushed_t CHECK (crushed_t BETWEEN 0 AND 50000),
    CONSTRAINT ck_plant_daily_milled_t CHECK (milled_t BETWEEN 0 AND 50000),
    CONSTRAINT ck_plant_daily_head_grade_gpt CHECK (head_grade_gpt BETWEEN 0 AND 50),
    CONSTRAINT ck_plant_daily_tails_grade_gpt CHECK (tails_grade_gpt BETWEEN 0 AND 10),
    CONSTRAINT ck_plant_daily_gravity_gold_oz CHECK (gravity_gold_oz BETWEEN 0 AND 5000),
    CONSTRAINT ck_plant_daily_gold_poured_oz CHECK (gold_poured_oz BETWEEN 0 AND 20000),
    CONSTRAINT ck_plant_daily_mill_run_h CHECK (mill_run_h BETWEEN 0 AND 24),
    CONSTRAINT ck_plant_daily_mill_planned_maint_h CHECK (mill_planned_maint_h BETWEEN 0 AND 24),
    CONSTRAINT ck_plant_daily_mill_unplanned_down_h CHECK (mill_unplanned_down_h BETWEEN 0 AND 24),
    CONSTRAINT ck_plant_daily_crusher_run_h CHECK (crusher_run_h BETWEEN 0 AND 24),
    CONSTRAINT ck_plant_daily_cyanide_kg CHECK (cyanide_kg BETWEEN 0 AND 50000),
    CONSTRAINT ck_plant_daily_lime_kg CHECK (lime_kg BETWEEN 0 AND 100000),
    CONSTRAINT ck_plant_daily_grinding_media_kg CHECK (grinding_media_kg BETWEEN 0 AND 50000),
    CONSTRAINT ck_plant_daily_power_kwh CHECK (power_kwh BETWEEN 0 AND 1000000),
    CONSTRAINT ck_plant_daily_raw_water_m3 CHECK (raw_water_m3 BETWEEN 0 AND 100000),
    CONSTRAINT ck_plant_daily_gic_oz CHECK (gic_oz BETWEEN 0 AND 50000)
);

-- Material movements, one row per source, material and destination per day (or per shift) (owner: Mining (dispatch / production engineer))
CREATE TABLE IF NOT EXISTS movement (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    shift TEXT,
    source TEXT NOT NULL,
    material TEXT NOT NULL,
    destination TEXT NOT NULL,
    tonnes_t NUMERIC(18,4) NOT NULL,
    grade_gpt NUMERIC(18,4),
    bcm NUMERIC(18,4),
    loads INTEGER,
    comments TEXT,
    is_ore INTEGER GENERATED ALWAYS AS (CASE WHEN material LIKE 'Ore%' THEN 1 ELSE 0 END) STORED,
    contained_oz NUMERIC(18,4) GENERATED ALWAYS AS (tonnes_t * COALESCE(grade_gpt, 0) / 31.1035) STORED,
    ore_oz NUMERIC(18,4) GENERATED ALWAYS AS (CASE WHEN material LIKE 'Ore%' THEN tonnes_t * COALESCE(grade_gpt, 0) / 31.1035 ELSE 0 END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT fk_movement_shift FOREIGN KEY (shift) REFERENCES ref_shift (code),
    CONSTRAINT fk_movement_source FOREIGN KEY (source) REFERENCES sources (source),
    CONSTRAINT fk_movement_material FOREIGN KEY (material) REFERENCES ref_material (code),
    CONSTRAINT fk_movement_destination FOREIGN KEY (destination) REFERENCES destinations (destination),
    CONSTRAINT ck_movement_tonnes_t CHECK (tonnes_t BETWEEN 0 AND 200000),
    CONSTRAINT ck_movement_grade_gpt CHECK (grade_gpt BETWEEN 0 AND 100),
    CONSTRAINT ck_movement_bcm CHECK (bcm BETWEEN 0 AND 100000),
    CONSTRAINT ck_movement_loads CHECK (loads BETWEEN 0 AND 5000)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_movement_key ON movement (date, COALESCE(shift, ''), source, material, destination);

-- Mining daily totals, one row per day (owner: Mining (production engineer))
CREATE TABLE IF NOT EXISTS mining_daily (
    date DATE NOT NULL,
    drill_m NUMERIC(18,4),
    blast_t NUMERIC(18,4),
    explosives_kg NUMERIC(18,4),
    diesel_l NUMERIC(18,4),
    dewatering_m3 NUMERIC(18,4),
    comments TEXT,
    powder_factor_kgpt NUMERIC(18,4) GENERATED ALWAYS AS (CASE WHEN blast_t > 0 THEN explosives_kg / blast_t END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_mining_daily PRIMARY KEY (date),
    CONSTRAINT ck_mining_daily_drill_m CHECK (drill_m BETWEEN 0 AND 20000),
    CONSTRAINT ck_mining_daily_blast_t CHECK (blast_t BETWEEN 0 AND 500000),
    CONSTRAINT ck_mining_daily_explosives_kg CHECK (explosives_kg BETWEEN 0 AND 200000),
    CONSTRAINT ck_mining_daily_diesel_l CHECK (diesel_l BETWEEN 0 AND 200000),
    CONSTRAINT ck_mining_daily_dewatering_m3 CHECK (dewatering_m3 BETWEEN 0 AND 500000)
);

-- Mining fleet time model, one row per equipment class per day (owner: Mining (dispatch / maintenance planner))
CREATE TABLE IF NOT EXISTS fleet (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    equipment_class TEXT NOT NULL,
    units INTEGER NOT NULL,
    down_h NUMERIC(18,4),
    operating_h NUMERIC(18,4),
    comments TEXT,
    calendar_h NUMERIC(18,4) GENERATED ALWAYS AS (units * 24) STORED,
    available_h NUMERIC(18,4) GENERATED ALWAYS AS (units * 24 - down_h) STORED,
    availability_pct NUMERIC(9,6) GENERATED ALWAYS AS (CASE WHEN units > 0 THEN (units * 24 - down_h) / (units * 24.0) END) STORED,
    utilisation_pct NUMERIC(9,6) GENERATED ALWAYS AS (CASE WHEN (units * 24 - down_h) > 0 THEN operating_h / (units * 24 - down_h) END) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT fk_fleet_equipment_class FOREIGN KEY (equipment_class) REFERENCES ref_equipment_class (code),
    CONSTRAINT ck_fleet_units CHECK (units BETWEEN 0 AND 200),
    CONSTRAINT ck_fleet_down_h CHECK (down_h BETWEEN 0 AND 4800),
    CONSTRAINT ck_fleet_operating_h CHECK (operating_h BETWEEN 0 AND 4800),
    CONSTRAINT uq_fleet_key UNIQUE (date, equipment_class)
);

-- Safety, health, environment and community, one row per day (owner: HSE)
CREATE TABLE IF NOT EXISTS safety_daily (
    date DATE NOT NULL,
    hours_employees NUMERIC(18,4),
    hours_contractors NUMERIC(18,4),
    fatality INTEGER,
    lti INTEGER,
    rwi INTEGER,
    mti INTEGER,
    fai INTEGER,
    near_miss INTEGER,
    hazard_reports INTEGER,
    hpi INTEGER,
    env_incidents INTEGER,
    community_incidents INTEGER,
    vehicle_incidents INTEGER,
    toolbox_talks INTEGER,
    inspections INTEGER,
    comments TEXT,
    hours_total NUMERIC(18,4) GENERATED ALWAYS AS (COALESCE(hours_employees, 0) + COALESCE(hours_contractors, 0)) STORED,
    recordables INTEGER GENERATED ALWAYS AS (COALESCE(fatality,0) + COALESCE(lti,0) + COALESCE(rwi,0) + COALESCE(mti,0)) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_safety_daily PRIMARY KEY (date),
    CONSTRAINT ck_safety_daily_hours_employees CHECK (hours_employees BETWEEN 0 AND 50000),
    CONSTRAINT ck_safety_daily_hours_contractors CHECK (hours_contractors BETWEEN 0 AND 50000),
    CONSTRAINT ck_safety_daily_fatality CHECK (fatality BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_lti CHECK (lti BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_rwi CHECK (rwi BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_mti CHECK (mti BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_fai CHECK (fai BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_near_miss CHECK (near_miss BETWEEN 0 AND 500),
    CONSTRAINT ck_safety_daily_hazard_reports CHECK (hazard_reports BETWEEN 0 AND 5000),
    CONSTRAINT ck_safety_daily_hpi CHECK (hpi BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_env_incidents CHECK (env_incidents BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_community_incidents CHECK (community_incidents BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_vehicle_incidents CHECK (vehicle_incidents BETWEEN 0 AND 50),
    CONSTRAINT ck_safety_daily_toolbox_talks CHECK (toolbox_talks BETWEEN 0 AND 500),
    CONSTRAINT ck_safety_daily_inspections CHECK (inspections BETWEEN 0 AND 500)
);

-- Prior-year safety history by month, for rolling 12-month rates (owner: HSE)
CREATE TABLE IF NOT EXISTS safety_history (
    month DATE NOT NULL,
    hours_total NUMERIC(18,4),
    recordables INTEGER,
    lti INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_safety_history PRIMARY KEY (month),
    CONSTRAINT ck_safety_history_month_first_of_month CHECK (EXTRACT(DAY FROM month) = 1),
    CONSTRAINT ck_safety_history_hours_total CHECK (hours_total BETWEEN 0 AND 2000000),
    CONSTRAINT ck_safety_history_recordables CHECK (recordables BETWEEN 0 AND 100),
    CONSTRAINT ck_safety_history_lti CHECK (lti BETWEEN 0 AND 100)
);

-- Gold shipments and sales (owner: Finance / gold room)
CREATE TABLE IF NOT EXISTS gold (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    type TEXT NOT NULL,
    dore_kg NUMERIC(18,4),
    gold_oz NUMERIC(18,4) NOT NULL,
    silver_oz NUMERIC(18,4),
    reference TEXT,
    comments TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT fk_gold_type FOREIGN KEY (type) REFERENCES ref_gold_movement_type (code),
    CONSTRAINT ck_gold_dore_kg CHECK (dore_kg BETWEEN 0 AND 5000),
    CONSTRAINT ck_gold_gold_oz CHECK (gold_oz BETWEEN 0 AND 100000),
    CONSTRAINT ck_gold_silver_oz CHECK (silver_oz BETWEEN 0 AND 100000)
);
CREATE INDEX IF NOT EXISTS ix_gold_date ON gold (date);

-- Monthly budget (or latest forecast), one row per month (owner: Technical services / finance)
CREATE TABLE IF NOT EXISTS budget (
    month DATE NOT NULL,
    ore_mined_t NUMERIC(18,4),
    ore_grade_gpt NUMERIC(18,4),
    waste_t NUMERIC(18,4),
    milled_t NUMERIC(18,4),
    head_grade_gpt NUMERIC(18,4),
    recovery_pct NUMERIC(9,6),
    gold_poured_oz NUMERIC(18,4),
    hours_worked NUMERIC(18,4),
    drill_m NUMERIC(18,4),
    diesel_l NUMERIC(18,4),
    days INTEGER GENERATED ALWAYS AS (EXTRACT(DAY FROM (date_trunc('month', month::timestamp) + INTERVAL '1 month - 1 day'))::integer) STORED,
    ore_oz NUMERIC(18,4) GENERATED ALWAYS AS (COALESCE(ore_mined_t,0) * COALESCE(ore_grade_gpt,0) / 31.1035) STORED,
    tmm_t NUMERIC(18,4) GENERATED ALWAYS AS (COALESCE(ore_mined_t,0) + COALESCE(waste_t,0)) STORED,
    feed_oz NUMERIC(18,4) GENERATED ALWAYS AS (COALESCE(milled_t,0) * COALESCE(head_grade_gpt,0) / 31.1035) STORED,
    recovered_oz NUMERIC(18,4) GENERATED ALWAYS AS (COALESCE(milled_t,0) * COALESCE(head_grade_gpt,0) / 31.1035 * COALESCE(recovery_pct,0)) STORED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT pk_budget PRIMARY KEY (month),
    CONSTRAINT ck_budget_month_first_of_month CHECK (EXTRACT(DAY FROM month) = 1),
    CONSTRAINT ck_budget_ore_mined_t CHECK (ore_mined_t BETWEEN 0 AND 5000000),
    CONSTRAINT ck_budget_ore_grade_gpt CHECK (ore_grade_gpt BETWEEN 0 AND 50),
    CONSTRAINT ck_budget_waste_t CHECK (waste_t BETWEEN 0 AND 20000000),
    CONSTRAINT ck_budget_milled_t CHECK (milled_t BETWEEN 0 AND 5000000),
    CONSTRAINT ck_budget_head_grade_gpt CHECK (head_grade_gpt BETWEEN 0 AND 50),
    CONSTRAINT ck_budget_recovery_pct CHECK (recovery_pct BETWEEN 0 AND 1),
    CONSTRAINT ck_budget_gold_poured_oz CHECK (gold_poured_oz BETWEEN 0 AND 500000),
    CONSTRAINT ck_budget_hours_worked CHECK (hours_worked BETWEEN 0 AND 2000000),
    CONSTRAINT ck_budget_drill_m CHECK (drill_m BETWEEN 0 AND 500000),
    CONSTRAINT ck_budget_diesel_l CHECK (diesel_l BETWEEN 0 AND 10000000)
);

-- Daily report narrative, one row per comment (owner: All departments; compiled by the production engineer)
CREATE TABLE IF NOT EXISTS commentary (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    area TEXT NOT NULL,
    comment TEXT NOT NULL,
    author TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    CONSTRAINT fk_commentary_area FOREIGN KEY (area) REFERENCES ref_area (code)
);
CREATE INDEX IF NOT EXISTS ix_commentary_date ON commentary (date);

-- ---------------------------------------------------------------- comments
COMMENT ON TABLE sources IS 'Sources (Excel tblSources)';
COMMENT ON COLUMN sources.source IS 'Source: Origin of a material movement: a pit or a stockpile';
COMMENT ON COLUMN sources.type IS 'Type: Pit = ex-pit (counts to TMM and strip ratio); Stockpile = rehandle';
COMMENT ON TABLE destinations IS 'Destinations (Excel tblDestinations)';
COMMENT ON COLUMN destinations.destination IS 'Destination: Where the material was delivered';
COMMENT ON COLUMN destinations.type IS 'Type: Stockpile = enters a stockpile balance; Plant = direct tip to crusher; Waste = dump';
COMMENT ON TABLE stockpiles IS 'Stockpiles (Excel tblStockpiles)';
COMMENT ON COLUMN stockpiles.stockpile IS 'Stockpile: Stockpile name; must match a Source and a Destination';
COMMENT ON COLUMN stockpiles.opening_t IS 'Opening_t [t]: Surveyed tonnes at the start of the year';
COMMENT ON COLUMN stockpiles.opening_gpt IS 'Opening_gpt [g/t]: Grade of the opening balance';
COMMENT ON COLUMN stockpiles.plant_feed IS 'Plant_Feed: Y if the plant draws its feed from this stockpile (milled tonnes are deducted)';
COMMENT ON COLUMN stockpiles.survey_date IS 'Survey_Date: Date of the opening survey';
COMMENT ON TABLE plant_daily IS 'Processing plant, one row per day (Excel tblPlant)';
COMMENT ON COLUMN plant_daily.date IS 'Date: Production day (day shift start to night shift end)';
COMMENT ON COLUMN plant_daily.crushed_t IS 'Crushed [t]: Dry tonnes through the primary crusher';
COMMENT ON COLUMN plant_daily.milled_t IS 'Milled [t]: Dry tonnes milled (mill feed weightometer)';
COMMENT ON COLUMN plant_daily.head_grade_gpt IS 'Head grade [g/t]: Mill feed grade from the daily metallurgical balance';
COMMENT ON COLUMN plant_daily.tails_grade_gpt IS 'Tails grade [g/t]: Final tails grade';
COMMENT ON COLUMN plant_daily.gravity_gold_oz IS 'Gravity gold [oz]: Gold recovered by the gravity circuit (part of total recovered)';
COMMENT ON COLUMN plant_daily.gold_poured_oz IS 'Gold poured [oz]: Fine gold in dore poured on the day';
COMMENT ON COLUMN plant_daily.mill_run_h IS 'Mill run hours [h]: Hours the mill was running';
COMMENT ON COLUMN plant_daily.mill_planned_maint_h IS 'Planned maintenance [h]: Planned maintenance downtime';
COMMENT ON COLUMN plant_daily.mill_unplanned_down_h IS 'Unplanned downtime [h]: Unplanned downtime (breakdowns, power, no feed)';
COMMENT ON COLUMN plant_daily.crusher_run_h IS 'Crusher run hours [h]: Primary crusher running hours';
COMMENT ON COLUMN plant_daily.cyanide_kg IS 'Cyanide [kg]: Sodium cyanide consumed';
COMMENT ON COLUMN plant_daily.lime_kg IS 'Lime [kg]: Lime consumed';
COMMENT ON COLUMN plant_daily.grinding_media_kg IS 'Grinding media [kg]: Grinding media added';
COMMENT ON COLUMN plant_daily.power_kwh IS 'Power [kWh]: Plant power consumed';
COMMENT ON COLUMN plant_daily.raw_water_m3 IS 'Raw water [m3]: Raw water drawn';
COMMENT ON COLUMN plant_daily.gic_oz IS 'Gold in circuit [oz]: Gold in circuit at end of day (point value, not additive)';
COMMENT ON COLUMN plant_daily.comments IS 'Comments: Short note; use the Commentary sheet for the report narrative';
COMMENT ON COLUMN plant_daily.feed_oz IS 'Contained gold in feed [oz]: Milled t x head grade / 31.1035';
COMMENT ON COLUMN plant_daily.tails_oz IS 'Gold lost to tails [oz]: Milled t x tails grade / 31.1035';
COMMENT ON COLUMN plant_daily.recovered_oz IS 'Gold recovered [oz]: Feed oz minus tails oz';
COMMENT ON COLUMN plant_daily.recovery_pct IS 'Recovery [%]: 1 minus tails grade over head grade';
COMMENT ON COLUMN plant_daily.throughput_tph IS 'Throughput [t/h]: Milled t per running hour';
COMMENT ON COLUMN plant_daily.availability_pct IS 'Mill availability [%]: (24 h minus planned and unplanned downtime) / 24 h';
COMMENT ON COLUMN plant_daily.utilisation_pct IS 'Mill utilisation [%]: Run hours over available hours';
COMMENT ON TABLE movement IS 'Material movements, one row per source, material and destination per day (or per shift) (Excel tblMovement)';
COMMENT ON COLUMN movement.date IS 'Date: Production day';
COMMENT ON COLUMN movement.shift IS 'Shift: Optional; leave blank for a daily total';
COMMENT ON COLUMN movement.source IS 'Source: Pit or stockpile the material came from (Lists sheet)';
COMMENT ON COLUMN movement.material IS 'Material: Ore grade class or waste type';
COMMENT ON COLUMN movement.destination IS 'Destination: Where the material went (Lists sheet)';
COMMENT ON COLUMN movement.tonnes_t IS 'Tonnes [t]: Dry tonnes moved (truck factor or weightometer)';
COMMENT ON COLUMN movement.grade_gpt IS 'Grade [g/t]: Grade control grade; required for ore and mineralised waste';
COMMENT ON COLUMN movement.bcm IS 'Volume [bcm]: Optional bank cubic metres';
COMMENT ON COLUMN movement.loads IS 'Truck loads: Optional truck count';
COMMENT ON COLUMN movement.comments IS 'Comments';
COMMENT ON COLUMN movement.is_ore IS 'Ore flag: 1 when Material starts with Ore';
COMMENT ON COLUMN movement.contained_oz IS 'Contained gold [oz]: Tonnes x grade / 31.1035, any material with a grade';
COMMENT ON COLUMN movement.ore_oz IS 'Ore gold [oz]: Contained oz for ore rows only';
COMMENT ON TABLE mining_daily IS 'Mining daily totals, one row per day (Excel tblMiningDaily)';
COMMENT ON COLUMN mining_daily.date IS 'Date';
COMMENT ON COLUMN mining_daily.drill_m IS 'Drilled [m]: Production drill metres';
COMMENT ON COLUMN mining_daily.blast_t IS 'Blasted [t]: Tonnes blasted';
COMMENT ON COLUMN mining_daily.explosives_kg IS 'Explosives [kg]: Explosives consumed';
COMMENT ON COLUMN mining_daily.diesel_l IS 'Diesel [L]: Mining fleet diesel';
COMMENT ON COLUMN mining_daily.dewatering_m3 IS 'Dewatering [m3]: Pit water pumped';
COMMENT ON COLUMN mining_daily.comments IS 'Comments';
COMMENT ON COLUMN mining_daily.powder_factor_kgpt IS 'Powder factor [kg/t]: Explosives kg per tonne blasted';
COMMENT ON TABLE fleet IS 'Mining fleet time model, one row per equipment class per day (Excel tblFleet)';
COMMENT ON COLUMN fleet.date IS 'Date';
COMMENT ON COLUMN fleet.equipment_class IS 'Equipment class';
COMMENT ON COLUMN fleet.units IS 'Units in fleet: Number of machines of this class on site';
COMMENT ON COLUMN fleet.down_h IS 'Down hours [h]: Sum of maintenance and breakdown hours across the class';
COMMENT ON COLUMN fleet.operating_h IS 'Operating hours [h]: Sum of engine or productive hours across the class';
COMMENT ON COLUMN fleet.comments IS 'Comments';
COMMENT ON COLUMN fleet.calendar_h IS 'Calendar hours [h]: Units x 24';
COMMENT ON COLUMN fleet.available_h IS 'Available hours [h]: Calendar minus down';
COMMENT ON COLUMN fleet.availability_pct IS 'Availability [%]: Available over calendar';
COMMENT ON COLUMN fleet.utilisation_pct IS 'Utilisation [%]: Operating over available';
COMMENT ON TABLE safety_daily IS 'Safety, health, environment and community, one row per day (Excel tblSafety)';
COMMENT ON COLUMN safety_daily.date IS 'Date';
COMMENT ON COLUMN safety_daily.hours_employees IS 'Hours worked, employees [h]';
COMMENT ON COLUMN safety_daily.hours_contractors IS 'Hours worked, contractors [h]';
COMMENT ON COLUMN safety_daily.fatality IS 'Fatalities';
COMMENT ON COLUMN safety_daily.lti IS 'Lost time injuries';
COMMENT ON COLUMN safety_daily.rwi IS 'Restricted work injuries';
COMMENT ON COLUMN safety_daily.mti IS 'Medical treatment injuries';
COMMENT ON COLUMN safety_daily.fai IS 'First aid injuries';
COMMENT ON COLUMN safety_daily.near_miss IS 'Near misses';
COMMENT ON COLUMN safety_daily.hazard_reports IS 'Hazard reports';
COMMENT ON COLUMN safety_daily.hpi IS 'High potential incidents';
COMMENT ON COLUMN safety_daily.env_incidents IS 'Environmental incidents';
COMMENT ON COLUMN safety_daily.community_incidents IS 'Community incidents or grievances';
COMMENT ON COLUMN safety_daily.vehicle_incidents IS 'Vehicle incidents';
COMMENT ON COLUMN safety_daily.toolbox_talks IS 'Toolbox talks';
COMMENT ON COLUMN safety_daily.inspections IS 'Inspections and audits';
COMMENT ON COLUMN safety_daily.comments IS 'Comments';
COMMENT ON COLUMN safety_daily.hours_total IS 'Hours worked, total [h]';
COMMENT ON COLUMN safety_daily.recordables IS 'Recordable injuries: Fatalities + LTI + RWI + MTI';
COMMENT ON TABLE safety_history IS 'Prior-year safety history by month, for rolling 12-month rates (Excel tblSafetyHistory)';
COMMENT ON COLUMN safety_history.month IS 'Month: First day of the month';
COMMENT ON COLUMN safety_history.hours_total IS 'Hours worked [h]';
COMMENT ON COLUMN safety_history.recordables IS 'Recordable injuries';
COMMENT ON COLUMN safety_history.lti IS 'Lost time injuries';
COMMENT ON TABLE gold IS 'Gold shipments and sales (Excel tblGold)';
COMMENT ON COLUMN gold.date IS 'Date';
COMMENT ON COLUMN gold.type IS 'Type: Shipment (dore leaves site) or Sale (refinery outturn sold)';
COMMENT ON COLUMN gold.dore_kg IS 'Dore weight [kg]';
COMMENT ON COLUMN gold.gold_oz IS 'Gold [oz]';
COMMENT ON COLUMN gold.silver_oz IS 'Silver [oz]';
COMMENT ON COLUMN gold.reference IS 'Reference: Shipment or sale reference';
COMMENT ON COLUMN gold.comments IS 'Comments';
COMMENT ON TABLE budget IS 'Monthly budget (or latest forecast), one row per month (Excel tblBudget)';
COMMENT ON COLUMN budget.month IS 'Month: First day of the month';
COMMENT ON COLUMN budget.ore_mined_t IS 'Ore mined [t]';
COMMENT ON COLUMN budget.ore_grade_gpt IS 'Ore grade mined [g/t]';
COMMENT ON COLUMN budget.waste_t IS 'Waste mined [t]';
COMMENT ON COLUMN budget.milled_t IS 'Milled [t]';
COMMENT ON COLUMN budget.head_grade_gpt IS 'Head grade [g/t]';
COMMENT ON COLUMN budget.recovery_pct IS 'Recovery [%]';
COMMENT ON COLUMN budget.gold_poured_oz IS 'Gold poured [oz]';
COMMENT ON COLUMN budget.hours_worked IS 'Hours worked [h]';
COMMENT ON COLUMN budget.drill_m IS 'Drilled [m]';
COMMENT ON COLUMN budget.diesel_l IS 'Mining diesel [L]';
COMMENT ON COLUMN budget.days IS 'Days in month';
COMMENT ON COLUMN budget.ore_oz IS 'Ore gold mined [oz]';
COMMENT ON COLUMN budget.tmm_t IS 'Total material moved [t]';
COMMENT ON COLUMN budget.feed_oz IS 'Contained gold in feed [oz]';
COMMENT ON COLUMN budget.recovered_oz IS 'Gold recovered [oz]';
COMMENT ON TABLE commentary IS 'Daily report narrative, one row per comment (Excel tblCommentary)';
COMMENT ON COLUMN commentary.date IS 'Date';
COMMENT ON COLUMN commentary.area IS 'Area';
COMMENT ON COLUMN commentary.comment IS 'Comment: One or two sentences; appears on the daily report';
COMMENT ON COLUMN commentary.author IS 'Author';

-- ---------------------------------------------------------------- audit: keep updated_at current
CREATE OR REPLACE FUNCTION mps_touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_sources_touch ON sources;
CREATE TRIGGER trg_sources_touch BEFORE UPDATE ON sources FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_destinations_touch ON destinations;
CREATE TRIGGER trg_destinations_touch BEFORE UPDATE ON destinations FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_stockpiles_touch ON stockpiles;
CREATE TRIGGER trg_stockpiles_touch BEFORE UPDATE ON stockpiles FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_plant_daily_touch ON plant_daily;
CREATE TRIGGER trg_plant_daily_touch BEFORE UPDATE ON plant_daily FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_movement_touch ON movement;
CREATE TRIGGER trg_movement_touch BEFORE UPDATE ON movement FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_mining_daily_touch ON mining_daily;
CREATE TRIGGER trg_mining_daily_touch BEFORE UPDATE ON mining_daily FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_fleet_touch ON fleet;
CREATE TRIGGER trg_fleet_touch BEFORE UPDATE ON fleet FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_safety_daily_touch ON safety_daily;
CREATE TRIGGER trg_safety_daily_touch BEFORE UPDATE ON safety_daily FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_safety_history_touch ON safety_history;
CREATE TRIGGER trg_safety_history_touch BEFORE UPDATE ON safety_history FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_gold_touch ON gold;
CREATE TRIGGER trg_gold_touch BEFORE UPDATE ON gold FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_budget_touch ON budget;
CREATE TRIGGER trg_budget_touch BEFORE UPDATE ON budget FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();
DROP TRIGGER IF EXISTS trg_commentary_touch ON commentary;
CREATE TRIGGER trg_commentary_touch BEFORE UPDATE ON commentary FOR EACH ROW EXECUTE FUNCTION mps_touch_updated_at();

-- ---------------------------------------------------------------- calculated views
DROP VIEW IF EXISTS kpi_monthly;
DROP VIEW IF EXISTS kpi_daily;
DROP VIEW IF EXISTS movement_calc;
CREATE VIEW movement_calc AS
SELECT t.*,
       j1.type AS source_type,
       j2.type AS dest_type
FROM movement t
LEFT JOIN sources j1 ON j1.source = t.source
LEFT JOIN destinations j2 ON j2.destination = t.destination;

-- ---------------------------------------------------------------- KPI views (workbook KPI catalogue)
-- Ex-pit = source type Pit; ore = material starting with Ore; rehandle = source type Stockpile.
-- Ratios are NULL when the denominator is zero. Sums are 0 on days without rows, as in the workbook.
CREATE VIEW kpi_daily AS
WITH days AS (
    SELECT date FROM movement UNION SELECT date FROM mining_daily UNION SELECT date FROM fleet UNION SELECT date FROM plant_daily UNION SELECT date FROM gold UNION SELECT date FROM safety_daily
),
agg_movement AS (
    SELECT date,
           SUM(CASE WHEN is_ore = 1 AND source_type = 'Pit' THEN tonnes_t ELSE 0 END) AS ore_mined_t,
           SUM(CASE WHEN source_type = 'Pit' THEN ore_oz ELSE 0 END) AS ore_mined_oz,
           SUM(CASE WHEN is_ore = 0 AND source_type = 'Pit' THEN tonnes_t ELSE 0 END) AS waste_t,
           SUM(CASE WHEN source_type = 'Stockpile' THEN tonnes_t ELSE 0 END) AS rehandle_t
    FROM movement_calc
    GROUP BY date
),
agg_mining_daily AS (
    SELECT date,
           SUM(drill_m) AS drill_m,
           SUM(blast_t) AS blast_t,
           SUM(explosives_kg) AS explosives_kg,
           SUM(diesel_l) AS diesel_mining_l,
           SUM(dewatering_m3) AS dewatering_m3
    FROM mining_daily
    GROUP BY date
),
agg_fleet AS (
    SELECT date,
           SUM(CASE WHEN equipment_class = 'Excavator' THEN calendar_h ELSE 0 END) AS exc_calendar_h,
           SUM(CASE WHEN equipment_class = 'Excavator' THEN available_h ELSE 0 END) AS exc_available_h,
           SUM(CASE WHEN equipment_class = 'Excavator' THEN operating_h ELSE 0 END) AS exc_operating_h,
           SUM(CASE WHEN equipment_class = 'Haul Truck' THEN calendar_h ELSE 0 END) AS trk_calendar_h,
           SUM(CASE WHEN equipment_class = 'Haul Truck' THEN available_h ELSE 0 END) AS trk_available_h,
           SUM(CASE WHEN equipment_class = 'Haul Truck' THEN operating_h ELSE 0 END) AS trk_operating_h
    FROM fleet
    GROUP BY date
),
agg_plant AS (
    SELECT date,
           SUM(crushed_t) AS crushed_t,
           SUM(milled_t) AS milled_t,
           SUM(feed_oz) AS feed_oz,
           SUM(tails_oz) AS tails_oz,
           SUM(recovered_oz) AS recovered_oz,
           SUM(gravity_gold_oz) AS gravity_gold_oz,
           SUM(gold_poured_oz) AS gold_poured_oz,
           SUM(mill_run_h) AS mill_run_h,
           SUM(mill_planned_maint_h) AS mill_planned_maint_h,
           SUM(mill_unplanned_down_h) AS mill_unplanned_down_h,
           COUNT(mill_run_h) * 24 AS mill_calendar_h,
           SUM(crusher_run_h) AS crusher_run_h,
           SUM(cyanide_kg) AS cyanide_kg,
           SUM(lime_kg) AS lime_kg,
           SUM(grinding_media_kg) AS grinding_media_kg,
           SUM(power_kwh) AS power_kwh,
           SUM(raw_water_m3) AS raw_water_m3,
           NULLIF(SUM(gic_oz), 0) AS gic_oz
    FROM plant_daily
    GROUP BY date
),
agg_gold AS (
    SELECT date,
           SUM(CASE WHEN type = 'Shipment' THEN gold_oz ELSE 0 END) AS gold_shipped_oz,
           SUM(CASE WHEN type = 'Sale' THEN gold_oz ELSE 0 END) AS gold_sold_oz,
           SUM(CASE WHEN type = 'Shipment' THEN dore_kg ELSE 0 END) AS dore_shipped_kg
    FROM gold
    GROUP BY date
),
agg_safety AS (
    SELECT date,
           SUM(hours_total) AS hours_worked,
           SUM(fatality) AS fatality,
           SUM(lti) AS lti,
           SUM(rwi) AS rwi,
           SUM(mti) AS mti,
           SUM(fai) AS fai,
           SUM(recordables) AS recordables,
           SUM(near_miss) AS near_miss,
           SUM(hazard_reports) AS hazard_reports,
           SUM(hpi) AS hpi,
           SUM(env_incidents) AS env_incidents,
           SUM(community_incidents) AS community_incidents,
           SUM(vehicle_incidents) AS vehicle_incidents,
           SUM(toolbox_talks) AS toolbox_talks,
           SUM(inspections) AS inspections
    FROM safety_daily
    GROUP BY date
),
base AS (
    SELECT d.date,
           COALESCE(a1.ore_mined_t, 0) AS ore_mined_t,
           COALESCE(a1.ore_mined_oz, 0) AS ore_mined_oz,
           COALESCE(a1.waste_t, 0) AS waste_t,
           COALESCE(a1.rehandle_t, 0) AS rehandle_t,
           COALESCE(a2.drill_m, 0) AS drill_m,
           COALESCE(a2.blast_t, 0) AS blast_t,
           COALESCE(a2.explosives_kg, 0) AS explosives_kg,
           COALESCE(a2.diesel_mining_l, 0) AS diesel_mining_l,
           COALESCE(a2.dewatering_m3, 0) AS dewatering_m3,
           COALESCE(a3.exc_calendar_h, 0) AS exc_calendar_h,
           COALESCE(a3.exc_available_h, 0) AS exc_available_h,
           COALESCE(a3.exc_operating_h, 0) AS exc_operating_h,
           COALESCE(a3.trk_calendar_h, 0) AS trk_calendar_h,
           COALESCE(a3.trk_available_h, 0) AS trk_available_h,
           COALESCE(a3.trk_operating_h, 0) AS trk_operating_h,
           COALESCE(a4.crushed_t, 0) AS crushed_t,
           COALESCE(a4.milled_t, 0) AS milled_t,
           COALESCE(a4.feed_oz, 0) AS feed_oz,
           COALESCE(a4.tails_oz, 0) AS tails_oz,
           COALESCE(a4.recovered_oz, 0) AS recovered_oz,
           COALESCE(a4.gravity_gold_oz, 0) AS gravity_gold_oz,
           COALESCE(a4.gold_poured_oz, 0) AS gold_poured_oz,
           COALESCE(a4.mill_run_h, 0) AS mill_run_h,
           COALESCE(a4.mill_planned_maint_h, 0) AS mill_planned_maint_h,
           COALESCE(a4.mill_unplanned_down_h, 0) AS mill_unplanned_down_h,
           COALESCE(a4.mill_calendar_h, 0) AS mill_calendar_h,
           COALESCE(a4.crusher_run_h, 0) AS crusher_run_h,
           COALESCE(a4.cyanide_kg, 0) AS cyanide_kg,
           COALESCE(a4.lime_kg, 0) AS lime_kg,
           COALESCE(a4.grinding_media_kg, 0) AS grinding_media_kg,
           COALESCE(a4.power_kwh, 0) AS power_kwh,
           COALESCE(a4.raw_water_m3, 0) AS raw_water_m3,
           a4.gic_oz AS gic_oz,
           COALESCE(a5.gold_shipped_oz, 0) AS gold_shipped_oz,
           COALESCE(a5.gold_sold_oz, 0) AS gold_sold_oz,
           COALESCE(a5.dore_shipped_kg, 0) AS dore_shipped_kg,
           COALESCE(a6.hours_worked, 0) AS hours_worked,
           COALESCE(a6.fatality, 0) AS fatality,
           COALESCE(a6.lti, 0) AS lti,
           COALESCE(a6.rwi, 0) AS rwi,
           COALESCE(a6.mti, 0) AS mti,
           COALESCE(a6.fai, 0) AS fai,
           COALESCE(a6.recordables, 0) AS recordables,
           COALESCE(a6.near_miss, 0) AS near_miss,
           COALESCE(a6.hazard_reports, 0) AS hazard_reports,
           COALESCE(a6.hpi, 0) AS hpi,
           COALESCE(a6.env_incidents, 0) AS env_incidents,
           COALESCE(a6.community_incidents, 0) AS community_incidents,
           COALESCE(a6.vehicle_incidents, 0) AS vehicle_incidents,
           COALESCE(a6.toolbox_talks, 0) AS toolbox_talks,
           COALESCE(a6.inspections, 0) AS inspections
    FROM days d
    LEFT JOIN agg_movement a1 ON a1.date = d.date
    LEFT JOIN agg_mining_daily a2 ON a2.date = d.date
    LEFT JOIN agg_fleet a3 ON a3.date = d.date
    LEFT JOIN agg_plant a4 ON a4.date = d.date
    LEFT JOIN agg_gold a5 ON a5.date = d.date
    LEFT JOIN agg_safety a6 ON a6.date = d.date
)
SELECT b.date,
       b.ore_mined_t,
       b.ore_mined_oz,
       CASE WHEN (b.ore_mined_t) > 0 THEN (b.ore_mined_oz*31.1035) / (b.ore_mined_t) END AS ore_grade_gpt,
       b.waste_t,
       b.ore_mined_t+b.waste_t AS tmm_t,
       CASE WHEN (b.ore_mined_t) > 0 THEN (b.waste_t) / (b.ore_mined_t) END AS strip_ratio,
       b.rehandle_t,
       b.drill_m,
       b.blast_t,
       b.explosives_kg,
       CASE WHEN (b.blast_t) > 0 THEN (b.explosives_kg) / (b.blast_t) END AS powder_factor_kgpt,
       b.diesel_mining_l,
       b.dewatering_m3,
       b.exc_calendar_h,
       b.exc_available_h,
       b.exc_operating_h,
       CASE WHEN (b.exc_calendar_h) > 0 THEN (b.exc_available_h) / (b.exc_calendar_h) END AS exc_availability_pct,
       CASE WHEN (b.exc_available_h) > 0 THEN (b.exc_operating_h) / (b.exc_available_h) END AS exc_utilisation_pct,
       b.trk_calendar_h,
       b.trk_available_h,
       b.trk_operating_h,
       CASE WHEN (b.trk_calendar_h) > 0 THEN (b.trk_available_h) / (b.trk_calendar_h) END AS trk_availability_pct,
       CASE WHEN (b.trk_available_h) > 0 THEN (b.trk_operating_h) / (b.trk_available_h) END AS trk_utilisation_pct,
       b.crushed_t,
       b.milled_t,
       b.feed_oz,
       b.tails_oz,
       b.recovered_oz,
       CASE WHEN (b.milled_t) > 0 THEN (b.feed_oz*31.1035) / (b.milled_t) END AS head_grade_gpt,
       CASE WHEN (b.milled_t) > 0 THEN (b.tails_oz*31.1035) / (b.milled_t) END AS tails_grade_gpt,
       CASE WHEN (b.feed_oz) > 0 THEN (b.recovered_oz) / (b.feed_oz) END AS recovery_pct,
       b.gravity_gold_oz,
       b.gold_poured_oz,
       b.mill_run_h,
       b.mill_planned_maint_h,
       b.mill_unplanned_down_h,
       b.mill_calendar_h,
       b.crusher_run_h,
       CASE WHEN (b.mill_run_h) > 0 THEN (b.milled_t) / (b.mill_run_h) END AS throughput_tph,
       CASE WHEN (b.mill_calendar_h) > 0 THEN (b.mill_calendar_h-b.mill_planned_maint_h-b.mill_unplanned_down_h) / (b.mill_calendar_h) END AS mill_availability_pct,
       CASE WHEN (b.mill_calendar_h-b.mill_planned_maint_h-b.mill_unplanned_down_h) > 0 THEN (b.mill_run_h) / (b.mill_calendar_h-b.mill_planned_maint_h-b.mill_unplanned_down_h) END AS mill_utilisation_pct,
       b.cyanide_kg,
       b.lime_kg,
       b.grinding_media_kg,
       b.power_kwh,
       b.raw_water_m3,
       CASE WHEN (b.milled_t) > 0 THEN (b.cyanide_kg) / (b.milled_t) END AS cyanide_kgpt,
       CASE WHEN (b.milled_t) > 0 THEN (b.lime_kg) / (b.milled_t) END AS lime_kgpt,
       CASE WHEN (b.milled_t) > 0 THEN (b.grinding_media_kg) / (b.milled_t) END AS media_kgpt,
       CASE WHEN (b.milled_t) > 0 THEN (b.power_kwh) / (b.milled_t) END AS power_kwhpt,
       CASE WHEN (b.milled_t) > 0 THEN (b.raw_water_m3) / (b.milled_t) END AS water_m3pt,
       b.gic_oz,
       b.gold_shipped_oz,
       b.gold_sold_oz,
       b.dore_shipped_kg,
       b.hours_worked,
       b.fatality,
       b.lti,
       b.rwi,
       b.mti,
       b.fai,
       b.recordables,
       b.near_miss,
       b.hazard_reports,
       b.hpi,
       b.env_incidents,
       b.community_incidents,
       b.vehicle_incidents,
       b.toolbox_talks,
       b.inspections,
       CASE WHEN ((SELECT COALESCE(SUM(s.hours_total), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.hours_total), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) > 0 THEN ((SELECT COALESCE(SUM(s.recordables), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.recordables), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) * 1000000 / ((SELECT COALESCE(SUM(s.hours_total), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.hours_total), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) END AS trifr_12m,
       CASE WHEN ((SELECT COALESCE(SUM(s.hours_total), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.hours_total), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) > 0 THEN ((SELECT COALESCE(SUM(s.lti), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.lti), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) * 1000000 / ((SELECT COALESCE(SUM(s.hours_total), 0) FROM safety_daily s WHERE s.date >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND s.date <= b.date) + (SELECT COALESCE(SUM(h.hours_total), 0) FROM safety_history h WHERE h.month >= (date_trunc('month', b.date::timestamp) - INTERVAL '12 months')::date AND h.month < date_trunc('month', b.date::timestamp)::date AND NOT EXISTS (SELECT 1 FROM safety_daily s2 WHERE date_trunc('month', s2.date::timestamp)::date = h.month))) END AS ltifr_12m,
       b.date - (SELECT MAX(s.date) FROM safety_daily s WHERE s.lti > 0 AND s.date <= b.date) AS days_since_lti
FROM base b;
CREATE VIEW kpi_monthly AS
SELECT date_trunc('month', k.date)::date AS month,
       COUNT(*) AS days_reported,
       SUM(k.ore_mined_t) AS ore_mined_t,
       SUM(k.ore_mined_oz) AS ore_mined_oz,
       CASE WHEN (SUM(k.ore_mined_t)) > 0 THEN (SUM(k.ore_mined_oz)*31.1035) / (SUM(k.ore_mined_t)) END AS ore_grade_gpt,
       SUM(k.waste_t) AS waste_t,
       SUM(k.tmm_t) AS tmm_t,
       CASE WHEN (SUM(k.ore_mined_t)) > 0 THEN (SUM(k.waste_t)) / (SUM(k.ore_mined_t)) END AS strip_ratio,
       SUM(k.rehandle_t) AS rehandle_t,
       SUM(k.drill_m) AS drill_m,
       SUM(k.blast_t) AS blast_t,
       SUM(k.explosives_kg) AS explosives_kg,
       CASE WHEN (SUM(k.blast_t)) > 0 THEN (SUM(k.explosives_kg)) / (SUM(k.blast_t)) END AS powder_factor_kgpt,
       SUM(k.diesel_mining_l) AS diesel_mining_l,
       SUM(k.dewatering_m3) AS dewatering_m3,
       SUM(k.exc_calendar_h) AS exc_calendar_h,
       SUM(k.exc_available_h) AS exc_available_h,
       SUM(k.exc_operating_h) AS exc_operating_h,
       CASE WHEN (SUM(k.exc_calendar_h)) > 0 THEN (SUM(k.exc_available_h)) / (SUM(k.exc_calendar_h)) END AS exc_availability_pct,
       CASE WHEN (SUM(k.exc_available_h)) > 0 THEN (SUM(k.exc_operating_h)) / (SUM(k.exc_available_h)) END AS exc_utilisation_pct,
       SUM(k.trk_calendar_h) AS trk_calendar_h,
       SUM(k.trk_available_h) AS trk_available_h,
       SUM(k.trk_operating_h) AS trk_operating_h,
       CASE WHEN (SUM(k.trk_calendar_h)) > 0 THEN (SUM(k.trk_available_h)) / (SUM(k.trk_calendar_h)) END AS trk_availability_pct,
       CASE WHEN (SUM(k.trk_available_h)) > 0 THEN (SUM(k.trk_operating_h)) / (SUM(k.trk_available_h)) END AS trk_utilisation_pct,
       SUM(k.crushed_t) AS crushed_t,
       SUM(k.milled_t) AS milled_t,
       SUM(k.feed_oz) AS feed_oz,
       SUM(k.tails_oz) AS tails_oz,
       SUM(k.recovered_oz) AS recovered_oz,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.feed_oz)*31.1035) / (SUM(k.milled_t)) END AS head_grade_gpt,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.tails_oz)*31.1035) / (SUM(k.milled_t)) END AS tails_grade_gpt,
       CASE WHEN (SUM(k.feed_oz)) > 0 THEN (SUM(k.recovered_oz)) / (SUM(k.feed_oz)) END AS recovery_pct,
       SUM(k.gravity_gold_oz) AS gravity_gold_oz,
       SUM(k.gold_poured_oz) AS gold_poured_oz,
       SUM(k.mill_run_h) AS mill_run_h,
       SUM(k.mill_planned_maint_h) AS mill_planned_maint_h,
       SUM(k.mill_unplanned_down_h) AS mill_unplanned_down_h,
       SUM(k.mill_calendar_h) AS mill_calendar_h,
       SUM(k.crusher_run_h) AS crusher_run_h,
       CASE WHEN (SUM(k.mill_run_h)) > 0 THEN (SUM(k.milled_t)) / (SUM(k.mill_run_h)) END AS throughput_tph,
       CASE WHEN (SUM(k.mill_calendar_h)) > 0 THEN (SUM(k.mill_calendar_h)-SUM(k.mill_planned_maint_h)-SUM(k.mill_unplanned_down_h)) / (SUM(k.mill_calendar_h)) END AS mill_availability_pct,
       CASE WHEN (SUM(k.mill_calendar_h)-SUM(k.mill_planned_maint_h)-SUM(k.mill_unplanned_down_h)) > 0 THEN (SUM(k.mill_run_h)) / (SUM(k.mill_calendar_h)-SUM(k.mill_planned_maint_h)-SUM(k.mill_unplanned_down_h)) END AS mill_utilisation_pct,
       SUM(k.cyanide_kg) AS cyanide_kg,
       SUM(k.lime_kg) AS lime_kg,
       SUM(k.grinding_media_kg) AS grinding_media_kg,
       SUM(k.power_kwh) AS power_kwh,
       SUM(k.raw_water_m3) AS raw_water_m3,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.cyanide_kg)) / (SUM(k.milled_t)) END AS cyanide_kgpt,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.lime_kg)) / (SUM(k.milled_t)) END AS lime_kgpt,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.grinding_media_kg)) / (SUM(k.milled_t)) END AS media_kgpt,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.power_kwh)) / (SUM(k.milled_t)) END AS power_kwhpt,
       CASE WHEN (SUM(k.milled_t)) > 0 THEN (SUM(k.raw_water_m3)) / (SUM(k.milled_t)) END AS water_m3pt,
       SUM(k.gold_shipped_oz) AS gold_shipped_oz,
       SUM(k.gold_sold_oz) AS gold_sold_oz,
       SUM(k.dore_shipped_kg) AS dore_shipped_kg,
       SUM(k.hours_worked) AS hours_worked,
       SUM(k.fatality) AS fatality,
       SUM(k.lti) AS lti,
       SUM(k.rwi) AS rwi,
       SUM(k.mti) AS mti,
       SUM(k.fai) AS fai,
       SUM(k.recordables) AS recordables,
       SUM(k.near_miss) AS near_miss,
       SUM(k.hazard_reports) AS hazard_reports,
       SUM(k.hpi) AS hpi,
       SUM(k.env_incidents) AS env_incidents,
       SUM(k.community_incidents) AS community_incidents,
       SUM(k.vehicle_incidents) AS vehicle_incidents,
       SUM(k.toolbox_talks) AS toolbox_talks,
       SUM(k.inspections) AS inspections
FROM kpi_daily k
GROUP BY date_trunc('month', k.date)::date;

-- ---------------------------------------------------------------- seed data (inserted only when missing)
INSERT INTO ref_shift (code, sort_order) VALUES ('Day', 1), ('Night', 2) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_material (code, sort_order) VALUES ('Ore HG', 1), ('Ore MG', 2), ('Ore LG', 3), ('Mineralised Waste', 4), ('Waste', 5), ('Topsoil', 6) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_area (code, sort_order) VALUES ('Safety', 1), ('Mining', 2), ('Geology', 3), ('Processing', 4), ('Maintenance', 5), ('Environment', 6), ('Community', 7), ('Supply', 8), ('People', 9), ('Projects', 10), ('General', 11) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_equipment_class (code, sort_order) VALUES ('Excavator', 1), ('Haul Truck', 2), ('Drill', 3), ('Dozer', 4), ('Grader', 5), ('Water Cart', 6), ('Wheel Loader', 7), ('Ancillary', 8) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_gold_movement_type (code, sort_order) VALUES ('Shipment', 1), ('Sale', 2) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_yes_no (code, sort_order) VALUES ('Y', 1), ('N', 2) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_source_type (code, sort_order) VALUES ('Pit', 1), ('Stockpile', 2) ON CONFLICT (code) DO NOTHING;
INSERT INTO ref_destination_type (code, sort_order) VALUES ('Stockpile', 1), ('Plant', 2), ('Waste', 3) ON CONFLICT (code) DO NOTHING;
INSERT INTO sources (source, type) VALUES ('Petowal Pit', 'Pit'), ('Satellite Pit', 'Pit'), ('ROM Pad', 'Stockpile'), ('Stockpile HG', 'Stockpile'), ('Stockpile MG', 'Stockpile'), ('Stockpile LG', 'Stockpile'), ('Mineralised Waste Dump', 'Stockpile') ON CONFLICT (source) DO NOTHING;
INSERT INTO destinations (destination, type) VALUES ('ROM Pad', 'Stockpile'), ('Crusher Direct Tip', 'Plant'), ('Stockpile HG', 'Stockpile'), ('Stockpile MG', 'Stockpile'), ('Stockpile LG', 'Stockpile'), ('Mineralised Waste Dump', 'Stockpile'), ('Waste Dump', 'Waste'), ('TSF Wall', 'Waste'), ('Topsoil Stockpile', 'Waste') ON CONFLICT (destination) DO NOTHING;
INSERT INTO stockpiles (stockpile, opening_t, opening_gpt, plant_feed, survey_date) VALUES ('ROM Pad', 0, 0, 'Y', NULL), ('Stockpile HG', 0, 0, 'N', NULL), ('Stockpile MG', 0, 0, 'N', NULL), ('Stockpile LG', 0, 0, 'N', NULL), ('Mineralised Waste Dump', 0, 0, 'N', NULL) ON CONFLICT (stockpile) DO NOTHING;
